# to use environment variables
spring.config.import=file:env.properties

spring.application.name=winslow

# Spring Security Credentials
# TODO : Next step will be to define this inside the Spring Security Config
spring.security.user.name=user
spring.security.user.password=password

# Database configuration
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
# Drop and Recreate all Tables to prevent error caused by the seed.sql trying to insert already existing data
spring.jpa.hibernate.ddl-auto=create
# Default data.sql -> We define seed.sql -> Without "classpath:" it does not work
spring.sql.init.data-locations=classpath:seed.sql

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}
spring.jpa.properties.hibernate.default_schema=winslow
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true