CREATE TABLE classrooms
(
    classroom_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location     VARCHAR(100)                             NOT NULL,
    room_number  VARCHAR(50)                              NOT NULL,
    capacity     INTEGER,
    CONSTRAINT pk_classrooms PRIMARY KEY (classroom_id)
);

CREATE TABLE courses
(
    course_id     VARCHAR(16)  NOT NULL,
    title         VARCHAR(255) NOT NULL,
    department_id INTEGER,
    CONSTRAINT pk_courses PRIMARY KEY (course_id)
);

CREATE TABLE enrollments
(
    student_id INTEGER NOT NULL,
    section_id INTEGER NOT NULL,
    CONSTRAINT pk_enrollments PRIMARY KEY (student_id, section_id)
);

CREATE TABLE instructors
(
    instructor_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname     VARCHAR(200)                             NOT NULL,
    lastname      VARCHAR(200)                             NOT NULL,
    department_id INTEGER,
    CONSTRAINT pk_instructors PRIMARY KEY (instructor_id)
);

CREATE TABLE sections
(
    section_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id    VARCHAR(16)                              NOT NULL,
    semester     VARCHAR(10),
    year         INTEGER,
    classroom_id INTEGER,
    CONSTRAINT pk_sections PRIMARY KEY (section_id)
);

CREATE TABLE time_slots
(
    time_slot_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time   time WITHOUT TIME ZONE                   NOT NULL,
    end_time     time WITHOUT TIME ZONE                   NOT NULL,
    day          VARCHAR(16)                              NOT NULL,
    CONSTRAINT pk_time_slots PRIMARY KEY (time_slot_id)
);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (department_id) ON DELETE SET NULL;

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_SECTION FOREIGN KEY (section_id) REFERENCES sections (section_id) ON DELETE CASCADE;

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE;

ALTER TABLE instructors
    ADD CONSTRAINT FK_INSTRUCTORS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (department_id) ON DELETE SET NULL;

ALTER TABLE sections
    ADD CONSTRAINT FK_SECTIONS_ON_CLASSROOM FOREIGN KEY (classroom_id) REFERENCES classrooms (classroom_id) ON DELETE SET NULL;

ALTER TABLE sections
    ADD CONSTRAINT FK_SECTIONS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE;